import type { ScriptTrack } from "@/types/learning";

export const kanji: ScriptTrack = {
  id: "kanji",
  title: "Kanji",
  japaneseTitle: "漢字",
  subtitle: "Build from there",
  description:
    "Characters that carry meaning, not just sound. You start with a small, high-value set built around numbers, people, and days, and grow it steadily.",
  intro:
    "Kanji are characters borrowed from Chinese that stand for meanings rather than single sounds. Most have more than one reading: an on'yomi, adapted from Chinese and usually used in compound words, and a kun'yomi, the native Japanese reading usually used when the character stands alone. You do not need to memorise every reading at once. Learn the meaning and the shape first, then pick up readings from the words you actually meet.",
  order: 3,
  lessons: [
    {
      slug: "numbers",
      title: "Numbers",
      subtitle: "一 二 三 四 五",
      summary:
        "The first five numbers, and the clearest example of on'yomi and kun'yomi living side by side.",
      characters: [
        {
          kind: "kanji",
          character: "一",
          meaning: "one",
          onyomi: ["イチ"],
          kunyomi: ["ひと(つ)"],
          radical: "一",
          note: "A single horizontal stroke. Counting objects uses ひとつ, while dates and compounds use イチ.",
          strokes: { count: 1 },
          examples: [
            { word: "一つ", reading: "ひとつ", romaji: "hitotsu", meaning: "one thing" },
            { word: "一月", reading: "いちがつ", romaji: "ichigatsu", meaning: "January" },
          ],
        },
        {
          kind: "kanji",
          character: "二",
          meaning: "two",
          onyomi: ["ニ"],
          kunyomi: ["ふた(つ)"],
          radical: "二",
          note: "Two strokes for two. The lower stroke is the longer of the pair.",
          strokes: { count: 2 },
          examples: [
            { word: "二つ", reading: "ふたつ", romaji: "futatsu", meaning: "two things" },
            { word: "二月", reading: "にがつ", romaji: "nigatsu", meaning: "February" },
          ],
        },
        {
          kind: "kanji",
          character: "三",
          meaning: "three",
          onyomi: ["サン"],
          kunyomi: ["みっ(つ)"],
          radical: "一",
          note: "Three strokes for three. The middle stroke is the shortest.",
          strokes: { count: 3 },
          examples: [
            { word: "三つ", reading: "みっつ", romaji: "mittsu", meaning: "three things" },
            { word: "三月", reading: "さんがつ", romaji: "sangatsu", meaning: "March" },
          ],
        },
        {
          kind: "kanji",
          character: "四",
          meaning: "four",
          onyomi: ["シ"],
          kunyomi: ["よん", "よっ(つ)"],
          radical: "囗",
          note: "The counting pattern stops here. よん is used far more often than シ, which sounds like the word for death.",
          strokes: { count: 5 },
          examples: [
            { word: "四つ", reading: "よっつ", romaji: "yottsu", meaning: "four things" },
            { word: "四月", reading: "しがつ", romaji: "shigatsu", meaning: "April" },
          ],
        },
        {
          kind: "kanji",
          character: "五",
          meaning: "five",
          onyomi: ["ゴ"],
          kunyomi: ["いつ(つ)"],
          radical: "二",
          note: "Common in prices, dates, and times, almost always read ゴ.",
          strokes: { count: 4 },
          examples: [
            { word: "五つ", reading: "いつつ", romaji: "itsutsu", meaning: "five things" },
            { word: "五月", reading: "ごがつ", romaji: "gogatsu", meaning: "May" },
          ],
        },
      ],
    },
    {
      slug: "people",
      title: "People",
      subtitle: "人 男 女 子 友",
      summary:
        "Characters for describing people. These turn up constantly in everyday words.",
      characters: [
        {
          kind: "kanji",
          character: "人",
          meaning: "person",
          onyomi: ["ジン", "ニン"],
          kunyomi: ["ひと"],
          radical: "人",
          note: "Two strokes resembling a walking figure. Added to a country's name it means a person from there.",
          strokes: { count: 2 },
          examples: [
            { word: "日本人", reading: "にほんじん", romaji: "nihonjin", meaning: "Japanese person" },
            { word: "一人", reading: "ひとり", romaji: "hitori", meaning: "one person, alone" },
          ],
        },
        {
          kind: "kanji",
          character: "男",
          meaning: "man, male",
          onyomi: ["ダン", "ナン"],
          kunyomi: ["おとこ"],
          radical: "田",
          note: "Built from 田 (rice field) above 力 (strength).",
          strokes: { count: 7 },
          examples: [
            { word: "男の子", reading: "おとこのこ", romaji: "otoko no ko", meaning: "boy" },
            { word: "男性", reading: "だんせい", romaji: "dansei", meaning: "male" },
          ],
        },
        {
          kind: "kanji",
          character: "女",
          meaning: "woman, female",
          onyomi: ["ジョ"],
          kunyomi: ["おんな"],
          radical: "女",
          note: "Also used as a building block inside many other kanji.",
          strokes: { count: 3 },
          examples: [
            { word: "女の子", reading: "おんなのこ", romaji: "onna no ko", meaning: "girl" },
            { word: "女性", reading: "じょせい", romaji: "josei", meaning: "female" },
          ],
        },
        {
          kind: "kanji",
          character: "子",
          meaning: "child",
          onyomi: ["シ"],
          kunyomi: ["こ"],
          radical: "子",
          note: "Appears at the end of many words and names.",
          strokes: { count: 3 },
          examples: [
            { word: "子ども", reading: "こども", romaji: "kodomo", meaning: "child" },
            { word: "女子", reading: "じょし", romaji: "joshi", meaning: "girl, women's" },
          ],
        },
        {
          kind: "kanji",
          character: "友",
          meaning: "friend",
          onyomi: ["ユウ"],
          kunyomi: ["とも"],
          radical: "又",
          note: "Usually met first in 友だち, the everyday word for friend.",
          strokes: { count: 4 },
          examples: [
            { word: "友だち", reading: "ともだち", romaji: "tomodachi", meaning: "friend" },
            { word: "友人", reading: "ゆうじん", romaji: "yūjin", meaning: "friend (formal)" },
          ],
        },
      ],
    },
    {
      slug: "days",
      title: "Days",
      subtitle: "日 月 火 水 木",
      summary:
        "These five open the days of the week, and 日 and 月 are among the most common kanji of all.",
      characters: [
        {
          kind: "kanji",
          character: "日",
          meaning: "sun, day",
          onyomi: ["ニチ", "ジツ"],
          kunyomi: ["ひ", "か"],
          radical: "日",
          note: "Originally a drawing of the sun. It carries both sun and day, and appears in the name of Japan itself.",
          strokes: { count: 4 },
          examples: [
            { word: "日本", reading: "にほん", romaji: "nihon", meaning: "Japan" },
            { word: "日よう日", reading: "にちようび", romaji: "nichiyōbi", meaning: "Sunday" },
          ],
        },
        {
          kind: "kanji",
          character: "月",
          meaning: "moon, month",
          onyomi: ["ゲツ", "ガツ"],
          kunyomi: ["つき"],
          radical: "月",
          note: "A crescent moon. Months are counted with it, which is why 一月 is January.",
          strokes: { count: 4 },
          examples: [
            { word: "月よう日", reading: "げつようび", romaji: "getsuyōbi", meaning: "Monday" },
            { word: "今月", reading: "こんげつ", romaji: "kongetsu", meaning: "this month" },
          ],
        },
        {
          kind: "kanji",
          character: "火",
          meaning: "fire",
          onyomi: ["カ"],
          kunyomi: ["ひ"],
          radical: "火",
          note: "Resembles a flame with sparks either side.",
          strokes: { count: 4 },
          examples: [
            { word: "火よう日", reading: "かようび", romaji: "kayōbi", meaning: "Tuesday" },
            { word: "花火", reading: "はなび", romaji: "hanabi", meaning: "fireworks" },
          ],
        },
        {
          kind: "kanji",
          character: "水",
          meaning: "water",
          onyomi: ["スイ"],
          kunyomi: ["みず"],
          radical: "水",
          note: "Suggests a stream with branches flowing off it.",
          strokes: { count: 4 },
          examples: [
            { word: "水よう日", reading: "すいようび", romaji: "suiyōbi", meaning: "Wednesday" },
            { word: "お水", reading: "おみず", romaji: "omizu", meaning: "water" },
          ],
        },
        {
          kind: "kanji",
          character: "木",
          meaning: "tree, wood",
          onyomi: ["モク", "ボク"],
          kunyomi: ["き"],
          radical: "木",
          note: "A tree with spreading roots. Two of them make 林, a wood.",
          strokes: { count: 4 },
          examples: [
            { word: "木よう日", reading: "もくようび", romaji: "mokuyōbi", meaning: "Thursday" },
            { word: "木", reading: "き", romaji: "ki", meaning: "tree" },
          ],
        },
      ],
    },
    {
      slug: "nature",
      title: "Nature",
      subtitle: "山 川 田 空 雨",
      summary:
        "Landscape characters. Several began as simple pictures, which makes them easy to remember.",
      characters: [
        {
          kind: "kanji",
          character: "山",
          meaning: "mountain",
          onyomi: ["サン"],
          kunyomi: ["やま"],
          radical: "山",
          note: "Three peaks. Common in place names and surnames.",
          strokes: { count: 3 },
          examples: [
            { word: "山", reading: "やま", romaji: "yama", meaning: "mountain" },
            { word: "富士山", reading: "ふじさん", romaji: "fujisan", meaning: "Mount Fuji" },
          ],
        },
        {
          kind: "kanji",
          character: "川",
          meaning: "river",
          onyomi: ["セン"],
          kunyomi: ["かわ"],
          radical: "川",
          note: "Three flowing lines of water.",
          strokes: { count: 3 },
          examples: [
            { word: "川", reading: "かわ", romaji: "kawa", meaning: "river" },
            { word: "川口", reading: "かわぐち", romaji: "kawaguchi", meaning: "river mouth" },
          ],
        },
        {
          kind: "kanji",
          character: "田",
          meaning: "rice field",
          onyomi: ["デン"],
          kunyomi: ["た"],
          radical: "田",
          note: "A field divided into plots. Extremely common in surnames.",
          strokes: { count: 5 },
          examples: [
            { word: "田んぼ", reading: "たんぼ", romaji: "tanbo", meaning: "rice paddy" },
            { word: "山田", reading: "やまだ", romaji: "yamada", meaning: "Yamada (surname)" },
          ],
        },
        {
          kind: "kanji",
          character: "空",
          meaning: "sky, empty",
          onyomi: ["クウ"],
          kunyomi: ["そら", "あ(く)"],
          radical: "穴",
          note: "Carries both sky and empty, which is why it appears in the word for airport.",
          strokes: { count: 8 },
          examples: [
            { word: "空", reading: "そら", romaji: "sora", meaning: "sky" },
            { word: "空港", reading: "くうこう", romaji: "kūkō", meaning: "airport" },
          ],
        },
        {
          kind: "kanji",
          character: "雨",
          meaning: "rain",
          onyomi: ["ウ"],
          kunyomi: ["あめ"],
          radical: "雨",
          note: "Drops falling from a cloud. It sits on top of other weather kanji such as 雪, snow.",
          strokes: { count: 8 },
          examples: [
            { word: "雨", reading: "あめ", romaji: "ame", meaning: "rain" },
            { word: "大雨", reading: "おおあめ", romaji: "ōame", meaning: "heavy rain" },
          ],
        },
      ],
    },
    {
      slug: "school",
      title: "School",
      subtitle: "学 校 先 生 本",
      summary:
        "Five characters that combine into the words you need on day one: 学校, 先生, 学生.",
      characters: [
        {
          kind: "kanji",
          character: "学",
          meaning: "study, learning",
          onyomi: ["ガク"],
          kunyomi: ["まな(ぶ)"],
          radical: "子",
          note: "A child under a roof. It starts most words about education.",
          strokes: { count: 8 },
          examples: [
            { word: "学校", reading: "がっこう", romaji: "gakkō", meaning: "school" },
            { word: "学生", reading: "がくせい", romaji: "gakusei", meaning: "student" },
          ],
        },
        {
          kind: "kanji",
          character: "校",
          meaning: "school",
          onyomi: ["コウ"],
          kunyomi: [],
          radical: "木",
          note: "Almost always seen paired with 学 in 学校. It has no common kun'yomi.",
          strokes: { count: 10 },
          examples: [
            { word: "学校", reading: "がっこう", romaji: "gakkō", meaning: "school" },
            { word: "高校", reading: "こうこう", romaji: "kōkō", meaning: "high school" },
          ],
        },
        {
          kind: "kanji",
          character: "先",
          meaning: "ahead, previous",
          onyomi: ["セン"],
          kunyomi: ["さき"],
          radical: "儿",
          note: "The sense of going before gives 先生, one who was born before you.",
          strokes: { count: 6 },
          examples: [
            { word: "先生", reading: "せんせい", romaji: "sensei", meaning: "teacher" },
            { word: "先月", reading: "せんげつ", romaji: "sengetsu", meaning: "last month" },
          ],
        },
        {
          kind: "kanji",
          character: "生",
          meaning: "life, birth",
          onyomi: ["セイ", "ショウ"],
          kunyomi: ["い(きる)", "う(まれる)", "なま"],
          radical: "生",
          note: "One of the most reading-heavy kanji for beginners. Learn it inside 先生 and 学生 first.",
          strokes: { count: 5 },
          examples: [
            { word: "先生", reading: "せんせい", romaji: "sensei", meaning: "teacher" },
            { word: "学生", reading: "がくせい", romaji: "gakusei", meaning: "student" },
          ],
        },
        {
          kind: "kanji",
          character: "本",
          meaning: "book, origin",
          onyomi: ["ホン"],
          kunyomi: ["もと"],
          radical: "木",
          note: "A tree with a mark at its base, meaning root or origin. That is the 本 in 日本.",
          strokes: { count: 5 },
          examples: [
            { word: "本", reading: "ほん", romaji: "hon", meaning: "book" },
            { word: "日本", reading: "にほん", romaji: "nihon", meaning: "Japan" },
          ],
        },
      ],
    },
  ],
};
